---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-secrets
  namespace: ci-cd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: coder-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: CODER_PG_CONNECTION_URL
      remoteRef:
        key: secret/data/ci-cd/coder
        property: CODER_PG_CONNECTION_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
