---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: langfuse
  namespace: observability
  labels:
    app.kubernetes.io/name: langfuse
    app.kubernetes.io/instance: langfuse
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`langfuse.lab`)
      kind: Rule
      services:
        - name: langfuse-web
          port: 3000
  tls:
    secretName: monster-server-cert
    options:
      name: mtls-strict
      namespace: traefik
