---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: comfyui
  namespace: ai-services
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`comfyui.svc.k8s.monster.lab`)
      kind: Rule
      services:
        - name: comfyui
          port: 8188
  tls:
    secretName: monster-server-cert
    options:
      name: mtls-strict
      namespace: ai-services
