---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-data
  namespace: ai-services
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
    app.kubernetes.io/part-of: ai-services
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-hdd
  resources:
    requests:
      storage: 200Gi
