---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dcgm-exporter-config
  namespace: observability
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  dcp-metrics-included.csv: |
    DCGM_FI_DEV_GPU_UTIL,field,utilization
    DCGM_FI_DEV_MEM_COPY_UTIL,field,utilization
    DCGM_FI_DEV_MEM_UTIL,field,utilization
    DCGM_FI_DEV_MEM_USED,field,memory
    DCGM_FI_DEV_MEM_FREE,field,memory
    DCGM_FI_DEV_TEMP,field,temperature
    DCGM_FI_DEV_POWER_USAGE,field,power
    DCGM_FI_DEV_POWER_LIMIT,field,power
    DCGM_FI_DEV_SM_CLOCK,field,clock
    DCGM_FI_DEV_MEM_CLOCK,field,clock
    DCGM_FI_DEV_PCIE_TX_THROUGHPUT,field,throughput
    DCGM_FI_DEV_PCIE_RX_THROUGHPUT,field,throughput
    DCGM_FI_DEV_GPU_TEMP_MAX,field,temperature
    DCGM_FI_DEV_ENC_UTIL,field,utilization
    DCGM_FI_DEV_DEC_UTIL,field,utilization
