---
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
  ports:
    - name: metrics
      port: 9400
      targetPort: 9400
      protocol: TCP
