---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: storage
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/part-of: storage
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-hdd
  resources:
    requests:
      storage: 200Gi
