---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: 50Gi
