apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: homelab
  source:
    repoURL: https://github.com/GDavij/homelab-gitops-k8s-cluster.git
    targetRevision: main
    path: "networking/ingress"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
