---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: secret/data/stack/rabbitmq
        property: RABBITMQ_DEFAULT_USER
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: secret/data/stack/rabbitmq
        property: RABBITMQ_DEFAULT_PASS
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None