---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 5s
        send_batch_size: 256
      memory_limiter:
        check_interval: 5s
        limit_mib: 192
        spike_limit_mib: 64

    exporters:
      prometheusremotewrite:
        endpoint: "https://metrics.lab:8443/api/v1/write"
        tls:
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
          ca_file: /certs/ca.crt
      otlp/jaeger:
        endpoint: "https://traces.lab:8443"
        tls:
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
          ca_file: /certs/ca.crt
      debug:
        verbosity: basic

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
