---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otel-secrets
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: otel-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: LANGFUSE_AUTH_BASE64
      remoteRef:
        key: observability/langfuse
        property: langfuse-auth-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
