---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: devenv-quota
  namespace: dev-env
  labels:
    app.kubernetes.io/name: devenv
    app.kubernetes.io/instance: devenv
    app.kubernetes.io/part-of: dev-env
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "6Gi"
    limits.cpu: "8"
    limits.memory: "8Gi"
    pods: "10"
    persistentvolumeclaims: "10"
