---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  namespace: ai-services
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/part-of: ai-services
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-hdd
  resources:
    requests:
      storage: 50Gi
