---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: langfuse-secrets
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: langfuse-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: secret/data/observability/langfuse
        property: NEXTAUTH_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SALT
      remoteRef:
        key: secret/data/observability/langfuse
        property: SALT
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: LANGFUSE_DB_URL
      remoteRef:
        key: secret/data/database/postgres
        property: LANGFUSE_DB_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: secret/data/storage/minio
        property: MINIO_ROOT_USER
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: secret/data/storage/minio
        property: MINIO_ROOT_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
