---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devenv-db-credentials
  namespace: dev-env
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: devenv-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/database/postgres
        property: POSTGRES_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
